POST http://localhost:6000/api/customer/signup http/1.1
Content-Type: application/json

{
    "username":"Kbb66",
    "fullname": "jamesjoe",
    "password": "kkkkkk",
    "email": "check@gmail.com",
    "address": "55 sham road"
}



